import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Receipt, Student } from '../types';

const fetchImageAsDataUrl = async (url: string): Promise<string> => {
  try {
    const response = await fetch(url, { mode: 'cors' });
    const blob = await response.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.warn('Failed to load logo for receipt PDF', error);
    return '';
  }
};

const formatDate = (value: any) => {
  if (!value) return new Date().toLocaleDateString();
  if (typeof value === 'string') return new Date(value).toLocaleDateString();
  if (value?.toDate) return value.toDate().toLocaleDateString();
  return new Date(value).toLocaleDateString();
};

export const printSchoolReceipt = async (student: Student, receipt: Receipt, totals: { paid: number; balance: number }) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const logo = await fetchImageAsDataUrl('https://i.ibb.co/LzYXwYfX/logo.png');

  doc.setFillColor(8, 18, 37);
  doc.rect(0, 0, pageWidth, 38, 'F');

  if (logo) {
    doc.addImage(logo, 'PNG', 14, 8, 20, 20);
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('CIRCLE OF HOPE ACADEMY', 40, 17);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Official School Receipt', 40, 24);
  doc.text('P.O. Box 3675, Ondangwa | +264 81 666 4074', pageWidth - 14, 14, { align: 'right' });
  doc.text('circleofhopeacademy@yahoo.com', pageWidth - 14, 20, { align: 'right' });

  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('RECEIPT', 14, 52);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Receipt No: ${receipt.number}`, 14, 60);
  doc.text(`Date: ${formatDate(receipt.generatedAt || receipt.createdAt || receipt.date)}`, pageWidth - 14, 60, { align: 'right' });

  autoTable(doc, {
    startY: 68,
    theme: 'grid',
    headStyles: { fillColor: [0, 29, 100], textColor: 255, fontStyle: 'bold' },
    bodyStyles: { textColor: 40, fontSize: 9 },
    body: [
      ['Student Name', student.name],
      ['Student ID', student.id],
      ['Class', student.assignedClass || student.grade || student.level || '-'],
      ['Parent / Guardian', student.parentName || '-'],
      ['Academic Year', receipt.academicYear || student.academicYear || new Date().getFullYear().toString()],
      ['Term', receipt.termId || '-'],
    ],
  });

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 8,
    theme: 'grid',
    head: [['Description', 'Amount (N$)']],
    headStyles: { fillColor: [0, 29, 100], textColor: 255, fontStyle: 'bold' },
    body: [
      ['School fee payment received', parseFloat(receipt.amount || '0').toFixed(2)],
      ['Total paid to date', totals.paid.toFixed(2)],
      ['Outstanding balance', totals.balance.toFixed(2)],
    ],
    columnStyles: {
      1: { halign: 'right' },
    },
  });

  const y = (doc as any).lastAutoTable.finalY + 16;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Verified by Circle of Hope Academy', 14, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated by ${receipt.generatedBy || 'Admin'} on ${formatDate(receipt.generatedAt || receipt.createdAt || receipt.date)}`, 14, y + 6);

  doc.save(`Receipt_${receipt.number}.pdf`);
};
